name: tmate
description: "A new Flutter project."

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.31.17
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  isar: ^3.1.0
  cryptography: ^2.7.0
  uuid: ^4.5.1
  collection: ^1.18.0
  flutter_ble_peripheral: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0
